# Generated by Django 3.1.12 on 2025-11-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='feedbackstaff',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='leavereport',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='staff_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceReport',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='FeedbackStaff',
        ),
        migrations.DeleteModel(
            name='LeaveReport',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
